import { INodeProps } from '@msdyn365-commerce-modules/utilities';
import { IBuyboxProps } from '../buybox.props.autogenerated';
import { IBuyboxData } from '../buybox.data';
// import readXlsxFile from 'read-excel-file';
import React from 'react';

export interface IBuyboxExcelImportViewProps {
    ContainerProps: INodeProps;
    input?: React.ReactNode;
}

const onChangeInputFileHandler = (e : any, props: IBuyboxProps<IBuyboxData>) => async () => {
    debugger;
};

export function getExcelImportControl(props: IBuyboxProps<IBuyboxData>): IBuyboxExcelImportViewProps | undefined{

    return {
        ContainerProps: {
            className: 'ms-buybox__deal-of-the-day'
        },
        input: (
            <div className="ms-buybox__deal-of-the-day-box">
               
               <input type="file" id="input" onChange={(e) => {onChangeInputFileHandler(e,props)}} />
            </div>
        )    
       
    };
}

